controller_joint_names: ['', 'joint1-1', 'joint1-2', 'joint1-3', 'joint2-1', 'j2-2', 'j2-3', 'j3-1', 'j3-2', 'j3-3', 'j1'-1', 'j1'-2', 'l1'-3', 'j3'-1', 'j3'-2', 'j3'-3', 'j2'-1', 'j2'-2', 'j2'-3', ]
